id: 1fc36f3c19234411af6c0ddb78889f7c
initial_creation_type: ebook
created_at: 4/10/2021
last_modified_at: 26/11/2021
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmpygkb_qt4.jpg
  credit: tmp5acq19mp.jpg
